DROP TABLE IF EXISTS "Notification" CASCADE;
DROP TABLE IF EXISTS "Favorite" CASCADE;
DROP TABLE IF EXISTS "Review" CASCADE;
DROP TABLE IF EXISTS "Reservation" CASCADE;
DROP TABLE IF EXISTS "SpaceAmenity" CASCADE;
DROP TABLE IF EXISTS "Space" CASCADE;
DROP TABLE IF EXISTS "Amenity" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;

CREATE TABLE "User" ("id" SERIAL,"name" TEXT NOT NULL,"email" TEXT NOT NULL,"password" TEXT NOT NULL,"role" TEXT DEFAULT 'USER',"status" BOOLEAN DEFAULT true,"createdAt" TIMESTAMP DEFAULT now(),"updatedAt" TIMESTAMP NOT NULL,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX ON "User"("email");

CREATE TABLE "Space" ("id" SERIAL,"name" TEXT NOT NULL,"description" TEXT,"location" TEXT NOT NULL,"capacity" INTEGER NOT NULL,"type" TEXT NOT NULL,"imageUrl" TEXT,"pricePerHour" NUMERIC DEFAULT 120,"status" BOOLEAN DEFAULT true,"createdAt" TIMESTAMP DEFAULT now(),"updatedAt" TIMESTAMP NOT NULL,PRIMARY KEY ("id"));

CREATE TABLE "Amenity" ("id" SERIAL,"name" TEXT NOT NULL UNIQUE,"icon" TEXT,PRIMARY KEY ("id"));

CREATE TABLE "SpaceAmenity" ("spaceId" INTEGER NOT NULL REFERENCES "Space"(id) ON DELETE CASCADE,"amenityId" INTEGER NOT NULL REFERENCES "Amenity"(id) ON DELETE CASCADE,PRIMARY KEY ("spaceId","amenityId"));

CREATE TABLE "Reservation" ("id" SERIAL,"userId" INTEGER NOT NULL REFERENCES "User"(id),"spaceId" INTEGER NOT NULL REFERENCES "Space"(id),"startTime" TIMESTAMP NOT NULL,"endTime" TIMESTAMP NOT NULL,"status" TEXT DEFAULT 'PENDING',"reason" TEXT,"createdAt" TIMESTAMP DEFAULT now(),"updatedAt" TIMESTAMP NOT NULL,PRIMARY KEY ("id"));

CREATE TABLE "Review" ("id" SERIAL,"userId" INTEGER NOT NULL REFERENCES "User"(id),"spaceId" INTEGER NOT NULL REFERENCES "Space"(id),"reservationId" INTEGER NOT NULL UNIQUE REFERENCES "Reservation"(id),"rating" INTEGER NOT NULL,"comment" TEXT NOT NULL,"createdAt" TIMESTAMP DEFAULT now(),PRIMARY KEY ("id"));

CREATE TABLE "Favorite" ("userId" INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,"spaceId" INTEGER NOT NULL REFERENCES "Space"(id) ON DELETE CASCADE,"createdAt" TIMESTAMP DEFAULT now(),PRIMARY KEY ("userId","spaceId"));

CREATE TABLE "Notification" ("id" SERIAL,"userId" INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,"title" TEXT NOT NULL,"message" TEXT,"type" TEXT DEFAULT 'INFO',"readAt" TIMESTAMP,"createdAt" TIMESTAMP DEFAULT now(),PRIMARY KEY ("id"));
CREATE INDEX ON "Notification"("userId","readAt");
